Repository fga-eps-mds/2020.1-VC_Gestor-BackEnd, pull requests merged in 2020-11, with the labels that each got.

#19 Issue 132 news creation
  packages/news/src/controller/NewsController.js
  packages/news/src/models/news.js
  packages/news/src/server.js
  psql-scripts/init-news-schema.sql
Labels: Desenvolvimento, MDS, User Story

#20 Issue 130 delete news
  packages/news/src/controller/NewsController.js
  packages/news/src/routes/news.routes.js
  packages/news/src/server.js
Labels: Desenvolvimento, MDS, User Story

#21 Issue 134 - Mudar dados do usuário logado
  packages/user/src/controller/AuthenticateUserService.js
  packages/user/src/controller/UserController.js
  packages/user/src/routes/users.routes.js
Labels: Desenvolvimento, MDS

#23 Issue 145 news test
  .gitignore
  .travis.yml
  packages/benefits/package-lock.json
  packages/benefits/package.json
  packages/benefits/src/controller/BenefitController.js
  packages/news/package-lock.json
  packages/news/package.json
  packages/news/src/controller/NewsController.js
  packages/news/src/models/news.js
  packages/news/src/routes/news.routes.js
  packages/news/src/test/ControllerTesting.spec.js
  packages/news/src/test/ModelTesting.spec.js
  packages/resolution/src/controller/PostController.js
  packages/resolution/src/controller/postService.js
  packages/resolution/src/models/post.js
  packages/resolution/src/test/controller/ControllerTesting.spec.js
  packages/resolution/src/test/controller/ModelTesting.spec.js
  packages/user/package-lock.json
  packages/user/package.json
Labels: Desenvolvimento, MDS

#25 Issue 152 test benefits
  .gitignore
  packages/benefits/package-lock.json
  packages/benefits/package.json
  packages/benefits/src/controller/BenefitController.js
  packages/benefits/src/controller/CreateBenefitResolve.js
  packages/benefits/src/controller/DeleteBenefitResolve.js
  packages/benefits/src/controller/FindAllBenefitsResolve.js
  packages/benefits/src/controller/FindByIdBenefitResolve.js
  packages/benefits/src/controller/UpdateBenefitResolve.js
  packages/benefits/src/routes/benefits.routes.js
  packages/benefits/src/test/BenefitsController.spec.js
  packages/benefits/src/test/ModelBenefits.spec.js
  packages/news/src/controller/CreateResolve.js
  packages/news/src/controller/DeleteNewsResolve.js
  packages/news/src/controller/FindAllResolve.js
  packages/news/src/controller/FindByIdResolve.js
  packages/news/src/controller/NewsController.js
  packages/news/src/controller/UpdateNewsResolve.js
  packages/news/src/test/ControllerTesting.spec.js
Labels: Desenvolvimento, enhancement
